CXX = clang++
SDL_HEADER = /opt/local/include
SDL_LIB = /opt/local/lib
SDL = -lSDL2 -L$(SDL_LIB)
# If your compiler is a bit older you may need to change -std=c++11 to -std=c++0x
CXXFLAGS = -Wall -c -std=c++14 -I$(SDL_HEADER)
LDFLAGS = $(SDL)
EXE = SDL_Lesson0

.PHONY: all
all: $(EXE)

$(EXE): main.o
	$(CXX) $(LDFLAGS) $< -o $@

main.o: main.cpp
	$(CXX) $(CXXFLAGS) $< -o $@

.PHONY: clean
clean:
	rm *.o && rm $(EXE)

